version: "3.9"
services: 
  laravel:
    build: .
    ports:
      - "8000:8000"
    volumes: 
      - ./sanctuary:/var/www/
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sanctuary
    ports:
      - 3306:3306
    volumes: 
      - ./mysql:/var/lib/mysql
  
       